# Generated by Django 4.1.1 on 2022-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HangryPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=40, verbose_name="Person First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=40, verbose_name="Person Last Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Person Email"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
            ],
            options={"verbose_name_plural": "Hangry Persons",},
        ),
    ]
